version: "3.8"

services:
  mysql-local:
    container_name: mysql-local
    image: mysql:8.0
    volumes:
      - ./mysql/mydir:/mydir
      - ./mysql/datadir:/var/lib/mysql
      # data source. you can put your sql file in this directory
      - ./mysql/source:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    ports:
      - 33306:3306
    restart: unless-stopped
